/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FootballTeamManagement;

import java.awt.HeadlessException;  
import java.sql.ResultSet;
import java.sql.SQLException; 
import javax.swing.JOptionPane;

/**
 *
 * @author jayakrishnan
 */
public class AddSponsor extends javax.swing.JFrame { 
    /**
     * Creates new form AddTeam
     */
    public AddSponsor() {
        initComponents();  
            dbhandler db=new dbhandler();
             try{
                ResultSet r = db.st.executeQuery("SELECT teamname FROM team");
               
                while(r.next())
                {
                  String Tname= r.getString(1);
                  Teamname.addItem(Tname);
                }
                r.close(); 
            }
            catch(Exception e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sponsorname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Repeatall = new javax.swing.JCheckBox();
        Teamname = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Player");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Sponsorname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sponsorname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Sponsorname.setToolTipText("");
        Sponsorname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Sponsor  Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N
        Sponsorname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Sponsorname.setSelectionColor(new java.awt.Color(255, 51, 51));
        Sponsorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SponsornameActionPerformed(evt);
            }
        });
        Sponsorname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SponsornameKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add New Sponsor");

        Amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Amount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Amount.setToolTipText("");
        Amount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Amount", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N
        Amount.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Amount.setSelectionColor(new java.awt.Color(255, 51, 51));
        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });
        Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AmountKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Repeatall.setBackground(new java.awt.Color(255, 255, 255));
        Repeatall.setText(" Repeat");
        Repeatall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatallActionPerformed(evt);
            }
        });

        Teamname.setBorder(null);
        Teamname.setOpaque(false);
        Teamname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Clear");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Amount, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(Teamname, javax.swing.GroupLayout.Alignment.LEADING, 0, 277, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Repeatall))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sponsorname, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Sponsorname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Teamname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Repeatall)
                    .addComponent(jLabel2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RepeatallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatallActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RepeatallActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Submit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            Submit();
        }
    }//GEN-LAST:event_AmountKeyPressed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    private void SponsornameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SponsornameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            Submit();
        }
    }//GEN-LAST:event_SponsornameKeyPressed

    private void SponsornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SponsornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SponsornameActionPerformed

    private void TeamnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamnameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AddSponsor().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSponsor().setVisible(true);
            }
        });
    }
    public void Submit(){
        
            dbhandler db=new dbhandler();
        String N=Sponsorname.getText(); 
        String T=String.valueOf(Teamname.getSelectedItem());
        String A=Amount.getText();
        if(N.length()==0){
            JOptionPane.showMessageDialog(this, "Specify Sponsor  Name");
            Sponsorname.requestFocus();
        }
        else if(!N.matches("^[a-zA-Z0-9_\\s]*$")){
            JOptionPane.showMessageDialog(this, "Sponsor  Name Should contain Alphabets ,numbers and white spaces only ");
            Sponsorname.requestFocus();
       }
       
        else if(A.length()==0){
            JOptionPane.showMessageDialog(this,"Specify Player rating ");
            Amount.requestFocus();
        }
        else if( (!checkIfNumber(A)) || (Long.parseLong(A)<1)   ){
            JOptionPane.showMessageDialog(this,"Amount must be at least 1");
            Amount.requestFocus();
        }
        else { 
            int count=1;
            int countsponsor=0;
            try{
                ResultSet r = db.st.executeQuery("SELECT COUNT(*) FROM sponsor");
                r.next();
                count= r.getInt(1)+1;
                r.close(); 
            }
            catch(Exception e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
            try{
                ResultSet r = db.st.executeQuery("SELECT COUNT(*) FROM sponsor where sponsorname='"+N+"'");
                r.next();
                countsponsor= r.getInt(1);
                r.close(); 
            }
            catch(Exception e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
    long Currentbudget=0;
    long Budget=0;
            try{
                ResultSet r = db.st.executeQuery("SELECT currentbudget FROM team where teamname='"+T+"'");
                r.next();
                Currentbudget= r.getInt(1);
                r.close(); 
            }
            catch(Exception e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
    Budget=Currentbudget+Long.parseLong(A);
            if(countsponsor!=0){
                JOptionPane.showMessageDialog(this," Name Already exist");
                Sponsorname.requestFocus();
            }
            else{   

try{
    
    
    String sql1=" INSERT INTO sponsor(sponsorid,sponsorname,sponsorteam,amount)   VALUES ("+count+",'"+N+"', '"+T+"',"+A+")";
    String sql2=" update  team set currentbudget="+Budget+" where teamname='"+T+"'  ";
           
    db.st.executeUpdate(sql1);
    db.st.executeUpdate(sql2);
            System.out.println("sponsor Added ");
            JOptionPane.showMessageDialog(this,"sponsor  Added ");
          if(Repeatall.isSelected()) { 
              AddSponsor S=new AddSponsor(); 
              S.setVisible(true);
              S.Repeatall.setSelected(true);
              
          } 
          this.dispose();
            }
            catch(SQLException | HeadlessException e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
        }
        }
        
        
    }
    
    
     public boolean checkIfNumber(String in) {
        
        try {
 
            Long.parseLong(in);
        
        } catch (NumberFormatException ex) {
            return false;
        }
        
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JCheckBox Repeatall;
    private javax.swing.JTextField Sponsorname;
    private javax.swing.JComboBox Teamname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
