/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FootballTeamManagement;

import java.awt.HeadlessException; 
import java.sql.ResultSet;
import java.sql.SQLException; 
import javax.swing.JOptionPane;

/**
 *
 * @author jayakrishnan
 */
public class AddTeam extends javax.swing.JFrame {
 
    /**
     * Creates new form AddTeam
     */
    public AddTeam() {
        initComponents();   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Teamname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Teamnbu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Repeatall = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Teamname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Teamname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Teamname.setToolTipText("");
        Teamname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Team Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N
        Teamname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Teamname.setSelectionColor(new java.awt.Color(255, 51, 51));
        Teamname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamnameActionPerformed(evt);
            }
        });
        Teamname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeamnameKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add New Team");

        Teamnbu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Teamnbu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Teamnbu.setToolTipText("");
        Teamnbu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Team budget( in millon)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N
        Teamnbu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Teamnbu.setSelectionColor(new java.awt.Color(255, 51, 51));
        Teamnbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamnbuActionPerformed(evt);
            }
        });
        Teamnbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TeamnbuKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 204)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Repeatall.setBackground(new java.awt.Color(255, 255, 255));
        Repeatall.setText(" Repeat");
        Repeatall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(Repeatall)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Teamname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Teamnbu))
                        .addContainerGap(125, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Teamname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Teamnbu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Repeatall))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-339)/2, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void TeamnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeamnameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            Submit();
        }
    }//GEN-LAST:event_TeamnameKeyPressed

    private void TeamnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamnameActionPerformed

    private void TeamnbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamnbuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamnbuActionPerformed

    private void TeamnbuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeamnbuKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            Submit();
        }
    }//GEN-LAST:event_TeamnbuKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            Submit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RepeatallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatallActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RepeatallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeam().setVisible(true);
            }
        });
    }
    public void Submit(){
        
        String N=Teamname.getText();
        String B = Teamnbu.getText();
        if(N.length()==0){
            JOptionPane.showMessageDialog(this, "Specify Team Name");
            Teamname.requestFocus();
        }
        else if(!N.matches("^[a-zA-Z0-9_\\s]*$")){
            JOptionPane.showMessageDialog(this, "Team Name Should contain Alphabets ,numbers and white spaces only ");
            Teamname.requestFocus();
       }
        else if(B.length()==0){
            JOptionPane.showMessageDialog(this,"Specify Team Base Budget");
            Teamnbu.requestFocus();
        }
        else if( (!checkIfNumber(B)) || (Long.parseLong(B)<=0.99)){
            JOptionPane.showMessageDialog(this,"Budget Mustbe a number and \n minimum amount is 1 million ");
            Teamnbu.requestFocus();
        }
        else { 
            int count=1;
            int countTeam=0;
            dbhandler db=new dbhandler();
            try{
                ResultSet r = db.st.executeQuery("SELECT COUNT(*) FROM team");
                r.next();
                count= r.getInt(1)+1;
                r.close(); 
            }
            catch(Exception e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
            try{
                ResultSet r = db.st.executeQuery("SELECT COUNT(*) FROM team where TEAMNAME='"+N+"'");
                r.next();
                countTeam= r.getInt(1);
                r.close(); 
            }
            catch(Exception e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
            if(countTeam!=0){
                JOptionPane.showMessageDialog(this,"Team Name Already exist");
                Teamname.requestFocus();
            }
            else{
                
                
                
                
                
                            try{
                ResultSet r = db.st.executeQuery("SELECT COUNT(*) FROM login where USERNAME='"+N+"'");
                r.next();
                countTeam= r.getInt(1);
                r.close(); 
            }
            catch(Exception e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
            if(countTeam!=0){
                JOptionPane.showMessageDialog(this,"Team Name Already exist in Login");
                Teamname.requestFocus();
            }
            else{
                
                
try{
            db.st.executeUpdate("INSERT INTO team(TEAMNO,TEAMNAME,CURRENTBUDGET,TOTALPLAYERS) " + 
                "VALUES ('"+count+"','"+N+"', '"+B+"',0)");
            db.st.executeUpdate("INSERT INTO login(USERNAME,PASSWORD,ISADMIN) " + 
                "VALUES ('"+N+"','"+N+"',0)");
             
            JOptionPane.showMessageDialog(this,"Team Added ");
            if(Repeatall.isSelected()) { 
              AddTeam A=new AddTeam(); 
              A.setVisible(true);
              A.Repeatall.setSelected(true);
              
          } 
            this.dispose();
            }
            catch(SQLException | HeadlessException e){
                System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error Occured \n\t["+e+"]");
            }
        }
        }
        }
        System.out.println(N);
        System.out.println(B);
        
        
    }
    
    
     public boolean checkIfNumber(String in) {
        
        try {
 
            Long.parseLong(in);
        
        } catch (NumberFormatException ex) {
            return false;
        }
        
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Repeatall;
    private javax.swing.JTextField Teamname;
    private javax.swing.JTextField Teamnbu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
